name: Run Coverage

on:
  pull_request:
    branches: [main] # or any branches you want to target
  push:
    branches: [main]

jobs:
  run_tests:
    name: Python (Pull Request Tests)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.12"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check Ruff
        run: uvx ruff check .

      - name: Check MyPy
        run: uv run mypy .
